name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Hola Mundo
        run: echo "hola mundo"

  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    
    steps:
      - name: Hola Mundo
        run: echo "hola mundo segundo"
