name: Deploy to server

on: push

jobs:
  first_job:
    name: Primer Job
    runs-on: ubuntu-latest

    env:
      NAME: Lifninif
    
    steps:
      - name: Hola Mundo
        run: echo "hola mundo $NAME"
      
      - name: Working dir
        run: ls -al
      
      - name: Action
        uses: actions/checkout@v4

  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    
    steps:
      - name: Hola Mundo
        run: echo "hola mundo segundo ${{ github.ref }}"

